AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  epos-proxy
  SAM Template for epos-proxy

Parameters: 
  EposTcpIpAddr: 
    Type: String
    Default: '79.79.1.47'
  EposTcpPort:
    Type: Number
    Default: 2022

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  EposOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Environment:
        Variables:
          TCP_IP: !Ref EposTcpIpAddr
          TCP_PORT: !Ref EposTcpPort
      CodeUri: epos_source/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        EposOrder:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /order
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EposOrderApi:
    Description: "API Gateway endpoint URL for Prod stage for Epos Order function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  EposOrderFunction:
    Description: "Epos Order Lambda Function ARN"
    Value: !GetAtt EposOrderFunction.Arn
  EposOrderFunctionIamRole:
    Description: "Implicit IAM Role created for Epos Order function"
    Value: !GetAtt EposOrderFunctionRole.Arn
